node {
    def path = '/home/fahmi/dicoding/a428-cicd-labs'
    def username = 'fahmi'
    def host = '127.0.0.1'
    docker.image('node:lts-buster-slim').inside('-p 3003:3000'){
    	stage('Build') {
            sh 'npm install'
    	}
    	stage('Test') {
            sh './jenkins/scripts/test.sh'
    	}
    	stage('Manual Approval') {
           input 'Continue in deploy stage?'
    	}
        stage('Deploy'){
            sh "ssh $username@$host 'cd $path; git pull origin master; git push heroku react-app:master'"
            sleep(60)
        }
    }
}
