node {
    checkout scm
    docker.image('node:lts-buster-slim').inside('-p 3000:3000'){
    	stage('Build') {
            sh 'yarn install'
    	}
    	stage('Test') {
            sh './jenkins/scripts/test.sh'
    	}
    	stage('Manual Approval') {
           input 'Continue in deploy stage?'
    	}
        stage('Deploy'){
            sh "git push heroku react-app:master"
            sleep(60)
        }
    }
}
